version: '3.7'

services:
  db:
    image: postgres:13.1
    container_name: db-boiler
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/
      - /tmp:/tmp
        #      - ./usr/bin:/usr/bin/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pgpasswd
      - POSTGRES_DB=docker
